"""empty message

Revision ID: 9b9049b63bfc
Revises: 9b35fa22c7a7
Create Date: 2023-05-11 06:38:31.640088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b9049b63bfc'
down_revision = '9b35fa22c7a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_students_id', table_name='students')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_students_id', 'students', ['id'], unique=False)
    # ### end Alembic commands ###
